#!/usr/bin/sh
#sudo apt install yad

/usr/bin/yad --notification --no-middle --command='gnome-system-monitor' --image=system-monitor-app-symbolic --text="Show system monitor" --menu='Show system monitor!gnome-system-monitor|Close system monitor!pkill -1 gnome-system-monitor -f -n|||About!firefox-esr https://doc.ubuntu-fr.org/yad_yet_another_dialog|Quit!quit'

