#!/bin/sh
#sudo apt install yad
#sudo apt install xdotool

yad --notification --no-middle --command="xdotool key --clearmodifiers Super+d" --image=user-desktop-symbolic --text="Show the desktop" --menu='Show the desktop!xdotool key --clearmodifiers Super+d||Quit!quit'


